#!/usr/bin/ruby
# frozen_string_literal: true

require 'json'
require 'tempfile'
require 'csv'
require 'optparse'
if system("gem list mediainfo -i > /dev/null")
  require 'mediainfo'
else
  puts "Required gem Mediainfo not found. Please install with: sudo gem install mediainfo"
  exit
end


# This controls option flags
# -p option allows you to select a custom mediaconch policy file - otherwise script uses default
# -e allows you to select a target file extenstion for the script to use.
# If no extenstion is specified it will target the default 'wav' extension. (Not case sensitive)
options = []
ARGV.options do |opts|
  opts.on('-p', '--Policy=val', String) { |val| POLICY_FILE = val }
  opts.on('-e', '--Extension=val', String) { |val| TARGET_EXTENSION = val.downcase }
  opts.on('-q', '--Quiet') { options << 'quiet' }
  opts.on('-m', '--meta-scan') { options << 'meta' }
  opts.on('-b', '--bext-scan') { options << 'bext' }
  opts.on('-s', '--signal-scan') { options << 'signal' }
  opts.on('-d', '--dropout-scan') { options << 'dropouts' }
  opts.on('-a', '--all') { options += ['meta', 'bext', 'signal', 'dropouts'] }
  opts.parse!
end

options += ['signal', 'meta'] if (options - ['quiet']).empty?

# set up arrays and variables
TARGET_EXTENSION = 'wav' unless defined? TARGET_EXTENSION

# Start embedded WAV Mediaconch policy section
# Policy derived from MediaConch Public Policies. Original Maintainer Peter B. License: CC-BY-4.0+
mc_policy = <<~EOS
  <?xml version="1.0"?>
  <policy type="and" name="Local Wave Policy" license="CC-BY-4.0+">
    <description>This is the common norm for WAVE audiofiles.&#xD;
  Any WAVs not matching this policy should be inspected and possibly normalized to conform to this.</description>
    <policy type="or" name="Signed Integer or Float?">
      <rule name="Is signed Integer?" value="Format_Settings_Sign" tracktype="Audio" occurrence="*" operator="=">Signed</rule>
      <rule name="Is floating point?" value="Format_Profile" tracktype="Audio" occurrence="*" operator="=">Float</rule>
    </policy>
    <policy type="and" name="Audio: Proper resolution?">
      <description>This policy defines audio-resolution values that are proper for WAV.</description>
      <policy type="or" name="Valid samplerate?">
        <description>This was not implemented as rule in order to avoid irregular sampling rates.</description>
        <!-- <rule name="Audio is 44.1 kHz?" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">44100</rule> -->
        <!-- <rule name="Audio is 48 kHz?" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">48000</rule> -->
        <!-- <rule name="Audio is 88.2 kHz?" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">88200</rule> -->
        <rule name="Audio is 96 kHz?" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">96000</rule>
        <!-- <rule name="Audio is 192 kHz?" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">192000</rule> -->
        <!-- <rule name="Audio is 11 kHz?" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">11025</rule> -->
        <!-- <rule name="Audio is 22.05 kHz?" value="SamplingRate" tracktype="Audio" occurrence="*" operator="=">22050</rule> -->
      </policy>
      <policy type="or" name="Valid bit depth?">
        <!-- <rule name="Audio is 16 bit?" value="BitDepth" tracktype="Audio" occurrence="*" operator="=">16</rule> -->
        <rule name="Audio is 24 bit?" value="BitDepth" tracktype="Audio" occurrence="*" operator="=">24</rule>
        <!-- <rule name="Audio is 32 bit?" value="BitDepth" tracktype="Audio" occurrence="*" operator="=">32</rule> -->
        <!-- <rule name="Audio is 8 bit?" value="BitDepth" tracktype="Audio" occurrence="*" operator="=">8</rule> -->
      </policy>
    </policy>
    <policy type="and" name="Is BFW?">
      <rule name="BEXT Exist?" value="Wave/Broadcast extension/" occurrence="*" operator="exists" scope="mmt"/>
    </policy>
    <policy type="and" name="Is BFW?">
      <rule name="No Padding" value="Wave/JUNK/" occurrence="*" operator="must not exist" scope="mmt"/>
    </policy>
    <policy type="and" name="Valid File Size?">
      <rule name="Size Limit" value="FileSize" tracktype="General" occurrence="*" operator="&lt;">4000000000</rule>
    </policy>
    <rule name="Container is RIFF (WAV)?" value="Format" tracktype="General" occurrence="*" operator="=">Wave</rule>
    <rule name="Encoding is linear PCM?" value="Format" tracktype="Audio" occurrence="*" operator="=">PCM</rule>
    <rule name="Audio is 'Little Endian'?" value="Format_Settings_Endianness" tracktype="Audio" occurrence="*" operator="=">Little</rule>
  </policy>
EOS
# End embedded WAV Mediaconch policy section

if TARGET_EXTENSION == 'wav'
  unless defined? POLICY_FILE
    POLICY_FILE = Tempfile.new('mediaConch')
    POLICY_FILE.write(mc_policy)
    POLICY_FILE.rewind
  end
end

class QcTarget
  def initialize(value)
    @input_path = value
    @warnings = []
  end

  # Function to scan file for mediaconch compliance
  def media_conch_scan(policy)
    if File.file?(policy)
      @qc_results = []
      policy_path = File.path(policy)
      command = 'mediaconch --Policy=' + '"' + policy_path + '" ' + '"' + @input_path + '"'
      media_conch_out = `#{command}`
      media_conch_out.strip!
      media_conch_out.split('/n').each {|qcline| @qc_results << qcline}
      @qc_results = @qc_results.to_s
      if File.exist?(policy)
        if @qc_results.include?('pass!')
          @qc_results = 'PASS'
        else
          @warnings << 'MEDIACONCH FAIL'
        end
      end
    else
      @qc_results = policy
    end
  end

  # Functions to scan audio stream characteristics
  # Function to get ffprobe json info
  def get_ffprobe
    ffprobe_command = 'ffprobe -print_format json -threads auto -show_entries frame_tags=lavfi.astats.Overall.Number_of_samples,lavfi.astats.Overall.Peak_level,lavfi.astats.Overall.Max_difference,lavfi.astats.Overall.Mean_difference,lavfi.astats.Overall.Peak_level,lavfi.aphasemeter.phase -f lavfi -i "amovie=' + "'" + @input_path + "'" + ',astats=reset=1:metadata=1,aphasemeter=video=0"'
    @ffprobe_out = JSON.parse(`#{ffprobe_command}`)
    @total_frame_count = @ffprobe_out['frames'].size
  end

  def normalize_time(time_source)
    Time.at(time_source).utc.strftime('%H:%M:%S:%m')
  end

  def get_mediainfo
    @mediainfo_out = MediaInfo.from(@input_path)
    @duration_normalized = Time.at(@mediainfo_out.audio.duration / 1000).utc.strftime('%H:%M:%S')
  end

  def qc_encoding_history
    if TARGET_EXTENSION == 'wav'
    @enc_hist_error = []
      unless @mediainfo_out.general.extra.nil?
        if @mediainfo_out.general.extra.bext_present == 'Yes' && @mediainfo_out.general.encoded_library_settings
          signal_chain_count = @mediainfo_out.general.encoded_library_settings.scan(/A=/).count
          if @mediainfo_out.audio.channels == 1
            unless @mediainfo_out.general.encoded_library_settings.scan(/mono/i).count == signal_chain_count
              @enc_hist_error << "BEXT Coding History channels don't match file"
            end
          end

          if @mediainfo_out.audio.channels == 2
            stereo_count = @mediainfo_out.general.encoded_library_settings.scan(/stereo/i).count
            dual_count = @mediainfo_out.general.encoded_library_settings.scan(/dual/i).count
            unless stereo_count + dual_count == signal_chain_count
              @enc_hist_error << "BEXT Coding History channels don't match file"
            end
          end
        end
      else
        @enc_hist_error << "Encoding history not present"
      end
      @warnings << @enc_hist_error if @enc_hist_error.size > 0
    end
  end

  def check_dropouts
    @sample_ratios = []
    @possible_drops = []
    @ffprobe_out['frames'].each do |frames|
      @sample_ratios << frames['tags']['lavfi.astats.Overall.Max_difference'].to_f / frames['tags']['lavfi.astats.Overall.Mean_difference'].to_f
    end
    @sample_ratios.each_with_index do |ratio, i|
      unless i + 1 == @sample_ratios.length
        diff_prior = (ratio - @sample_ratios[i - 1]).abs
        diff_post = (ratio - @sample_ratios[i + 1]).abs
        if diff_prior > 15 && diff_post > 15
          @possible_drops << normalize_time(i * @ffprobe_out['frames'][0]['tags']['lavfi.astats.Overall.Number_of_samples'].to_f / @mediainfo_out.audio.samplingrate) 
        end
      end
    end
    @warnings << "Possible Dropouts Detected" if @possible_drops.length > 0
  end

  def find_peaks_n_phase
    high_db_frames = []
    out_of_phase_frames = []
    phase_frames = []
    @levels = []
    @ffprobe_out['frames'].each do |frames|
      peaklevel = frames['tags']['lavfi.astats.Overall.Peak_level'].to_f
      audiophase = frames['tags']['lavfi.aphasemeter.phase'].to_f
      phase_frames << audiophase
      out_of_phase_frames << audiophase if audiophase < -0.25
      high_db_frames << peaklevel if peaklevel > -2.0
      @levels << peaklevel
    end
    @max_level = @levels.max.round(2)
    @high_level_count = high_db_frames.size
    @average_levels = (@levels.sum(0.0) / @levels.size).round(2)
    @phasey_frame_count = out_of_phase_frames.size
    @average_phase = (phase_frames.sum(0.0) / phase_frames.size).round(2)
    @warnings << 'LEVEL WARNING' if @high_level_count > 0
    @warnings << 'PHASE WARNING' if @phasey_frame_count > 50
  end
  def output_csv_line(options)
    line = [@input_path, @warnings.flatten, @duration_normalized]
    if options.include? 'dropouts'
      line << @possible_drops
    end
    if options.include? 'signal'
      line += [@average_levels, @max_level, @high_level_count, @average_phase, @phasey_frame_count]
    end
    if options.include? 'meta'
      line << @qc_results
    end
    return line
  end
  def output_warnings
    @warnings
  end
end

# Make list of inputs
file_inputs = []
write_to_csv = []
ARGV.each do |input|
  # If input is directory, recursively add all files with target extension to target list
  if File.directory?(input)
    targets = Dir["#{input}/**/*.{#{TARGET_EXTENSION.upcase},#{TARGET_EXTENSION.downcase}}"]
    targets.each do |file|
      file_inputs << file
    end
  # If input is file, add it to target list (if extension matches target extension)
  elsif File.extname(input).downcase == '.' + TARGET_EXTENSION.downcase && File.exist?(input)
    file_inputs << input
  else
    puts "Input: #{input} not found!"
  end
end

if file_inputs.empty?
  puts 'No targets found!'
  exit
end

file_inputs.each do |fileinput|
  target = QcTarget.new(File.expand_path(fileinput))
  target.get_mediainfo
  if options.include? 'meta'
    if defined? POLICY_FILE
      target.media_conch_scan(POLICY_FILE)
    else
      target.media_conch_scan('Valid Policy File Not Found')
    end
  end
  if options.include? 'bext'
    target.qc_encoding_history
  end
  if options.include?('signal') || options.include?('dropouts')
    target.get_ffprobe
    if options.include? 'signal'
      target.find_peaks_n_phase
    end
    if options.include? 'dropouts'
      target.check_dropouts
    end
  end
  if options.include? 'quiet'
    if target.output_warnings.empty?
      puts 'QC Pass!'
      exit 0
    else
      puts 'QC Fail!'
      puts target.output_warnings
      exit 1
    end
  else
    write_to_csv << target.output_csv_line(options)
  end
end

timestamp = Time.now.strftime('%Y-%m-%d_%H-%M-%S')
output_csv = ENV['HOME'] + "/Desktop/audioqc-out_#{timestamp}.csv"

CSV.open(output_csv, 'wb') do |csv|
  headers = ['Filename', 'Warnings', 'Duration']
  if options.include? 'dropouts'
    headers << 'Possible Drops'
  end

  if options.include? 'signal'
   headers += ['Average Level', 'Peak Level', 'Number of Frames w/ High Levels', 'Average Phase', 'Number of Phase Warnings']
  end

  if options.include? 'meta'
    headers <<  'MediaConch Policy Compliance'
  end
  csv << headers
  write_to_csv.each do |line|
    csv << line
  end
end
